feat: Update model architecture and multiprocessing
mihirkatare/DeepMEM pull request #16
Opened 2021-10-10 22:04 UTC by mihirkatare

- Add multiprocessing support for the dataloader (cache-based multiprocessing)
- Add residual network architectures 
- Separate model and networks for scalability
- Add draft of API arguments to README

2021-10-12 05:46 UTC, matthewfeickert requested changes
@mihir-katare This looks good overall. :+1: I've put some small comments in.

Do we need to keep the contents of `post/` in version control? They're all binaries, so unless there is a necessity to have them be versioned I'd suggest instead attaching them as artifacts to a GitHub release.

2021-10-12 05:46 UTC, matthewfeickert commented on model.py
> +from networks import *
In general we should always avoid doing `import *` as this basically totally destroys our namespace and makes it much more difficult to understand how changes in APIs propagate in the future. Can we explicitly give the imports here?

2021-10-12 05:46 UTC, matthewfeickert commented on model.py
> +        # plt.savefig(self.manager.args["save_testing_histogram_at"])
```suggestion
```

Probably better to remove code rather than have commended out code in version control.

2021-10-12 05:46 UTC, matthewfeickert commented on model.py
> +        plt.grid()
This is fine for now, but we can go and specify which axis objects we want this applied to later on rather than using the `plt` API.

2021-10-17 22:38 UTC, mihirkatare commented
> @mihirkatare Do we need to keep the contents of `post/` in version control? They're all binaries, so unless there is a necessity to have them be versioned I'd suggest instead attaching them as artifacts to a GitHub release (which for the time being would mean copying out elsewhere to keep).

We mention that the library will be pip-installable. Does that include the pre-trained models? i.e the .pth binaries

2021-10-17 22:43 UTC, mihirkatare commented
Okay the binaries have been removed from main

2021-10-18 00:04 UTC, merged